---
- import_tasks: install-server.yml
  become: true
- import_tasks: secure-db.yml
  become: true
- import_tasks: replication.yml
  when: mariadb_replication
  become: true
- name: Start MariaDB
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
    enabled: true
  become: true
